apiVersion: v1
kind: Namespace
metadata:
  name: photo-viewer
  labels:
    name: photo-viewer
---
apiVersion: v1
kind: Secret
metadata:
  name: env-secret
  namespace: photo-viewer
type: Opaque
data:
  DB_ROOT_PW:
  DB_USER:
  DB_PASSWORD:
  DB_NAME:
  JWT_TOKEN_SECRET:
  JWT_REFRESH_TOKEN_SECRET: