apiVersion: v1
kind: Service
metadata:
  name: locust-master
  namespace: photo-viewer
spec:
  selector:
    app: locust
    role: master
  ports:
  - name: web
    port: 8089
    targetPort: 8089
  - name: master
    port: 5557
    targetPort: 5557
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  namespace: photo-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
      role: master
  template:
    metadata:
      labels:
        app: locust
        role: master
    spec:
      containers:
      - image: drigrgly/load-testing:latest
        name: locust-master
        ports:
        - containerPort: 8089
          name: web
        - containerPort: 5557
          name: master
        command: ["locust"]
        args:
          - "-f"
          - "locustfile.py"
          - "--master"
          - "--host"
          - "http://photo-viewer-service.photo-viewer:3000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  namespace: photo-viewer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: locust
      role: worker
  template:
    metadata:
      labels:
        app: locust
        role: worker
    spec:
      containers:
      - image: drigrgly/load-testing:latest
        name: locust-worker
        env:
        - name: LOAD_TEST_USER
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: LOAD_TEST_USER
        - name: LOAD_TEST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: LOAD_TEST_PASSWORD
        command: ["locust"]
        args:
          - "-f"
          - "locustfile.py"
          - "--worker"
          - "--master-host"
          - "locust-master"
          - "--master-port"
          - "5557"
          - "--host"
          - "http://photo-viewer-service.photo-viewer:3000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
